// Package mcpgw renders the routes file of vd-mcpgw, the agentgateway instance
// in front of apps' database MCPs when they are deployed with --mcp-oauth.
//
// One gateway, one file, one route per app, selected by host. agentgateway
// watches the file and applies route changes live; only the top-level `config:`
// section is read at start (docs/plans/forward-auth.md, stacks phase 0). The
// file is replaced atomically and validated by the same image first: a broken
// file would take OAuth down for every app at once.
package mcpgw

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/vibe-deploy/vd/internal/shell"
)

// Image is pinned to the digest stacks runs (dev-ops/stacks versions.sh).
const Image = "cr.agentgateway.dev/agentgateway:v1.5.0@sha256:bf2f339ef326d32def2aaeb44b1b4549801293c19b89e764a4228667d97d9896"

// Route is one app's MCP resource.
type Route struct {
	Name     string // mcp-vibe-<app>: audience, client id, required group
	Host     string // <app>.mcp.<domain>
	Resource string // https://<app>.mcp.<domain>/mcp
	Issuer   string // https://<authentik>/application/o/mcp-vibe-<app>/
	Backend  string // http://vd-<app>-mcp:8089/sse
}

var tmpl = template.Must(template.New("gw").Parse(`# Auto-generated by vd. Do not edit manually — vd rewrites it on every
# deploy and destroy of an app with --mcp-oauth.
#
# Revocation delay equals the token lifetime (5 minutes): the gateway reads
# signed claims, not live membership. Removing a route, or the app, is the
# immediate lever.
config:
  dns:
    # Docker's embedded DNS answers A only; asking for both families turns every
    # backend lookup into "backends required DNS resolution which failed".
    lookupFamily: V4Only
binds:
- port: 3000
  listeners:
  - routes:
{{- range .}}
    - name: {{printf "%q" .Name}}
      hostnames: [{{printf "%q" .Host}}]
      matches:
      - path: {exact: /mcp}
      - path: {exact: /.well-known/oauth-protected-resource/mcp}
      - path: {exact: /.well-known/oauth-authorization-server/mcp}
      - path: {exact: /.well-known/oauth-authorization-server/mcp/client-registration}
      policies:
        mcpAuthentication:
          mode: strict
          issuer: {{printf "%q" .Issuer}}
          audiences: [{{printf "%q" .Name}}]
          provider: {authentik: {}}
          clientId: {{printf "%q" .Name}}
          resourceMetadata:
            resource: {{printf "%q" .Resource}}
            scopesSupported: [openid, mcp, offline_access]
            bearerMethodsSupported: [header]
        authorization:
          # Second line of defence: a token for another resource is refused here
          # even if someone bound its audience wrongly.
          rules: ['has(jwt.groups) && "{{.Name}}" in jwt.groups']
      backends:
      - mcp:
          targets:
          - name: db
            # One URI string: the host/port/path form validates and then fails at
            # request time (stacks phase 0).
            sse: {host: {{printf "%q" .Backend}}}
{{- end}}
    - name: "fallback"
      policies:
        directResponse: {status: 404, body: "No MCP resource on this host"}
`))

// Render returns the file for these routes, in a stable order.
func Render(routes []Route) (string, error) {
	rs := append([]Route(nil), routes...)
	sort.Slice(rs, func(i, j int) bool { return rs[i].Name < rs[j].Name })
	for _, r := range rs {
		for _, v := range []string{r.Name, r.Host, r.Resource, r.Issuer, r.Backend} {
			if v == "" || strings.ContainsAny(v, "\"'\n\\") {
				return "", fmt.Errorf("route %q has an empty or unsafe value %q", r.Name, v)
			}
		}
	}
	var b strings.Builder
	if err := tmpl.Execute(&b, rs); err != nil {
		return "", err
	}
	return b.String(), nil
}

// Validate asks the gateway image whether the routes file in stageDir is
// acceptable. It runs on vd-net, like the live gateway, because --validate-only
// fetches every issuer's JWKS and must see the network the gateway sees.
// Tests replace it.
var Validate = func(stageDir string) error {
	r, err := shell.Run(30*time.Second, "docker", "run", "--rm", "--network", "vd-net",
		"-v", stageDir+":/etc/agentgateway:ro",
		Image, "-f", "/etc/agentgateway/config.yaml", "--validate-only")
	if err != nil {
		return fmt.Errorf("%v: %s%s", err, r.Stdout, r.Stderr)
	}
	return nil
}

// Write replaces dir/config.yaml atomically with routes the gateway accepts.
// A route the gateway rejects on its own — typically an issuer whose JWKS
// cannot be fetched — is left out and returned in dropped, so one app's
// broken issuer does not freeze every other app's routes, and a destroyed
// app's route is removed regardless. If every route fails on its own the
// cause is not the routes (Authentik is down, the image is missing): the old
// file is kept and an error returned.
func Write(dir string, routes []Route) (dropped []string, err error) {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, err
	}
	stage, err := os.MkdirTemp(dir, ".stage-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(stage)
	if err := os.Chmod(stage, 0755); err != nil {
		return nil, err
	}
	staged := filepath.Join(stage, "config.yaml")
	try := func(rs []Route) error {
		body, err := Render(rs)
		if err != nil {
			return err
		}
		if err := os.WriteFile(staged, []byte(body), 0644); err != nil {
			return err
		}
		return Validate(stage)
	}

	if err := try(routes); err != nil {
		if len(routes) == 0 {
			return nil, fmt.Errorf("gateway rejected the routes file, old one kept: %w", err)
		}
		var keep []Route
		for _, r := range routes {
			if try([]Route{r}) == nil {
				keep = append(keep, r)
			} else {
				dropped = append(dropped, r.Name)
			}
		}
		if len(keep) == 0 {
			return nil, fmt.Errorf("gateway rejected every route, old file kept (Authentik unreachable?): %w", err)
		}
		if err := try(keep); err != nil {
			return nil, fmt.Errorf("gateway rejected the routes file, old one kept: %w", err)
		}
	}
	// Same directory, so rename is atomic and the watcher sees one complete file.
	return dropped, os.Rename(staged, filepath.Join(dir, "config.yaml"))
}
